require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
 TargetRubyVersion: 3.1
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'

Documentation:
 Enabled: false

Metrics/BlockLength:
 ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Metrics/LineLength:
  Max: 80

AsciiComments:
  Enabled: false
